---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:
    "{ .Release.Name }": null
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name:
    "{ .Release.Name }": null
apiGroup: rbac.authorization.k8s.io
