---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:
    "{ .Release.Name }": null
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
