---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username:
    "{ .Values.secrets.db.username | b64enc }": null
  password:
    "{ .Values.secrets.db.password | b64enc }": null
