---
apiVersion: v1
kind: Service
metadata:
  name:
    "{ .Release.Name }": null
  labels:
    app:
      "{ .Chart.Name }": null
spec:
  type:
    "{ .Values.service.type }": null
  ports:
    - port:
        "{ .Values.service.port }": null
      targetPort: 80
  selector:
    app:
      "{ .Chart.Name }": null
